name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sast-scan:
    name: SAST w/ Semgrep
    runs-on: ubuntu-latest
    container:
      # Do not change this.
      image: semgrep/semgrep
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        continue-on-error: false

  dast-scan:
    name: DAST w/ ZAP
    runs-on: ubuntu-latest
    needs: [sast-scan]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build and run Django container
        run: |
          docker build -f noteproject/Dockerfile -t django-server noteproject
          docker run --rm -d -p 8000:8000 --name django-server django-server
      - name: Wait for Django to Start
        run: sleep 10
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-full-scan@v0.12.0
        #env:
        #  ZAP_AUTH_HEADER_VALUE: 'Basic dXNlcjpwYXNzd29yZAo='
        #  ZAP_AUTH_HEADER: 'Authorization'
        with:
          #token: ${{ secrets.REPO_TOKEN }}
          target: 'http://localhost:8000'
          cmd_options: '-a --hook=$(pwd)/auth_hook.py'
          fail_action: 'true'
        continue-on-error: false
